{
 "title": "New dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Memory, Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Free memory, Gb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes / 1024 /1024 /1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free disk space, Gb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU LA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "(node_load15 / on(instance) group_left count(node_cpu_seconds_total{mode=\"idle\"}) by (instance)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "утилизация CPU (в процентах 100-idle)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "100- (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m]))*100)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}