---
  - name: clickhouse
    src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.13"
  - name: lighthouse-role
    src: git@github.com:fedinly/ansible-lighthouse-role.git
    scm: git
    version: "1.1.0"
  - name: vector-role
    src: git@github.com:fedinly/ansible-vector-role.git
    scm: git
    version: "1.1.0"
