apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace }}
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Страница для решения ДЗ</title> # ИЗМЕНИТЕ: Заголовок страницы
    </head>
    <body>
      <h1>Решение ДЗ по теме «helm»</h1>
    </body>
    </html>

  nginx.conf: |
    server {
      listen 80;
      server_name test.int;
      root /var/www/html;

      # Add index.html at the beginning of the list
      index index.html index.htm;

      location / {
        try_files $uri $uri/ =404;
      }
    }
