apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: helm
spec:
  selector:
    app: netology-app
  type: ClusterIP
  ports:
  - port: {{ .Values.service.frontend.port }}
    name: http
    protocol: TCP
    targetPort: 80
