apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
  type: ClusterIP
  ports:
  - port: {{ .Values.service.backend.port }}
    name: multitool
    protocol: TCP
    targetPort: 8080
