apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
  type: ClusterIP
  ports:
  - port: {{ .Values.service.frontend.port }}
    name: http
    protocol: TCP
    targetPort: 80
